// Re-download the self-hosted typeface.
//
// The product uses one family, and it is served from this origin rather than from Google —
// see the comment in index.html for why. That means the files are checked in, and this is
// how they are regenerated when the family, the weights or the subsets change.
//
//   npm run --workspace client fonts:fetch
//
// It asks Google Fonts for the CSS a modern browser would get (the user agent decides
// whether that is woff2), downloads every face it names, and rewrites the stylesheet to
// point at the local copies.
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(here, '../public/fonts');

const FAMILY = 'Poppins';
const WEIGHTS = [300, 400, 500, 600, 700, 800];

// Asking as Chrome is what gets woff2 rather than the ttf served to unknown clients.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const url = `https://fonts.googleapis.com/css2?family=${FAMILY}:wght@${WEIGHTS.join(';')}&display=swap`;

const css = await fetch(url, { headers: { 'user-agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts answered ${r.status}`);
  return r.text();
});

await fs.mkdir(outDir, { recursive: true });

const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*@font-face \{(.*?)\}/gs)];
if (blocks.length === 0) throw new Error('No @font-face blocks in the response — the CSS format changed.');

let bytes = 0;
const rewritten = [];

for (const [, subset, body] of blocks) {
  const weight = /font-weight: (\d+)/.exec(body)?.[1];
  const remote = /url\((https:\/\/[^)]+)\)/.exec(body)?.[1];
  if (!weight || !remote) continue;

  const name = `poppins-${subset}-${weight}.woff2`;
  const data = Buffer.from(await fetch(remote, { headers: { 'user-agent': UA } }).then((r) => r.arrayBuffer()));
  await fs.writeFile(path.join(outDir, name), data);
  bytes += data.length;

  rewritten.push(`/* ${subset} */\n@font-face {${body.replace(remote, `/fonts/${name}`)}}`);
}

const header = `/* ${FAMILY}, self-hosted.
   Generated by scripts/fetch-fonts.mjs from the Google Fonts CSS2 response, with every
   remote URL rewritten to a local file. Self-hosted so the application has no external
   origin at all: no request to a third party on every page load, no font host in the
   content security policy, and no dependency on a network the reader may not have. */\n\n`;

await fs.writeFile(path.join(outDir, 'poppins.css'), header + rewritten.join('\n') + '\n');

console.log(`${rewritten.length} faces, ${(bytes / 1024).toFixed(0)} KB → public/fonts/`);
